name: Run unit tests 🧪

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize]
  
jobs:
  run_unit_tests:
      runs-on: ubuntu-latest
      steps:  
        - uses: actions/checkout@v2

        - name: Update Rust toolchain
          run: |
            rustup update stable
            rustup component add clippy

        - name: Print toolchain information
          run: |
            rustc --version
            cargo --version
            rustup --version
            cargo clippy --version
        
        - name: Lint
          run: | 
            cargo fmt -- --check
            cargo clippy -- -D warnings

        - name: Test
          run: |
            cargo check
            cargo test --all